### ISSUE TITLE
State/Province Name Spelling

### ISSUE THREAD

**Issue by jyin191** [dotnetprog/PCF-CanadaPost-AddressComplete#2]
It works great, Thanks for that - Just one quick observation, when an address is being keyed in, the province/state is spelled in abbreviation, but once  populated, it is fully spelled out, am wondering if you can keep the retrieved field in abbreviation.
eg. during lookup, the address is displayed as "113 Homestead Street, Spring Valley, NY 10977", but once populated, NY is translated to "New York" (having said that, there may be situations where fully spelling is preferred, so a setting will be ideal)

**Comment by dotnetprog** [comment]
New version has been released and available form the solution directory, a new setting has been added accordingly so that you can either choose the province code or province name

Here's a demo:
![image](https://user-images.githubusercontent.com/24593889/86859473-b3a54d80-c090-11ea-9f6c-8a4c7d1395ff.png)
